# Generated by Django 6.0.1 on 2026-02-13 18:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('registration_time', models.DateTimeField(auto_now_add=True)),
                ('owned_by', models.CharField(max_length=100)),
                ('vendor_contact', models.CharField(max_length=15)),
                ('owner_contact', models.CharField(max_length=15)),
                ('menu_count', models.IntegerField(default=0)),
                ('terms_agreed_at', models.DateTimeField(blank=True, null=True)),
                ('volume_processed', models.IntegerField(default=0)),
                ('value_processed', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('status', models.CharField(default='Active', max_length=20)),
                ('registered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_vendors', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
