# Generated by Django 6.0.1 on 2026-02-13 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='eta',
            field=models.IntegerField(default=5, help_text='Estimated time of arrival in minutes'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='ratings',
            field=models.FloatField(default=5),
        ),
    ]
