# Generated by Django 6.0.3 on 2026-03-31 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0004_menu_date_added_menu_status_alter_vendor_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='ratings',
        ),
        migrations.AddField(
            model_name='vendor',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='rating',
            field=models.FloatField(default=5),
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
