# Generated by Django 6.0.3 on 2026-03-31 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_placement', '0002_alter_order_vendor_order_assigned_drone_delete_menu_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='amount_paid',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_time',
        ),
        migrations.AddField(
            model_name='order',
            name='image_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
